### ISSUE TITLE
您好，我用的是yolov5-6.1的仓库，转完engine后，执行 `./yolov5` 出现了下面的报错

### ISSUE THREAD

**Issue by xunxuntu** [yhwang-hub/dl_model_deploy#2]
engine_file: ../yolov5s.engine
Read trt engine success
deserialize done
index[0], input shape: 1 x 3 x 640 x 640, input_buf_size: 4915200
error: 3: Cannot find binding of given name: output0
error: 3: [engine.cpp::getBindingDimensions::1307] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/engine.cpp::getBindingDimensions::1307, condition: bindIndex >= 0 && bindIndex < getNbBindings()
)
index[-1], output shape: 1 x 0 x 0, output_buffer_size: 0
Inference det [640 x 640] constructed
input_image shape: [640, 640]
preprocess time: 4.31362 ms.
Pre-process done!
Segmentation fault (core dumped)

**Comment by yhwang-hub** [comment]
修改一下代码中输入输出的name和你自己的模型对应上
